name: Deployment Workflow
on:
  push:
    branches: [ master ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing jfaden.net server ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: jfaden.net
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.OMG_SECRET }}
        port: 887
        script: |
          echo $HOSTNAME
          cd /var/www/cottagesystems.com/autoplot/git/uri-templates
          git pull origin master
          git status
          echo "==="
          cd /var/www/cottagesystems.com/autoplot/git/uri-templates/UriTemplatesJava
          export JAVA_HOME=/usr/local/jdk1.8
          ant clean jar
          echo "see https://cottagesystems.com/autoplot/git/uri-templates/UriTemplatesJava/dist/UriTemplatesJava.jar"
