name: Deployment Workflow
on:
  push:
    branches: [ main ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing jfaden.net server ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: jfaden.net
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.OMG_SECRET }}
        port: 887
        script: |
          echo $HOSTNAME
          cd /var/www/cottagesystems.com/autoplot/git/server-java
          git pull origin main
          git status
          echo "==="
          cd /var/www/cottagesystems.com/autoplot/git/server-java/HapiServerBase
          ant clean jar
          echo "see https://cottagesystems.com/autoplot/git/server-java/HapiServerBase/dist/HapiServerBase.jar"          
          echo "==="
          cd /var/www/cottagesystems.com/autoplot/git/server-java/HapiServer
          ant -Dj2ee.server.home=/usr/local/apache-tomcat-8/ clean dist
          echo "see https://cottagesystems.com/autoplot/git/server-java/HapiServer/dist/HapiServer.war"          
          echo "==="
          cd /var/www/cottagesystems.com/autoplot/git/server-java/SimpleClasspathExtension
          ant clean jar
          echo "see https://cottagesystems.com/autoplot/git/server-java/SimpleClasspathExtension/dist/SimpleClasspathExtension.jar"
          echo "==="
